### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by msabolova149** [TIS2021-FMFI/pomocky-a-skolenia#1]

**Comment by tymian11** [comment]
[Katalóg požiadaviek.docx](https://github.com/TIS2021-FMFI/pomocky-a-skolenia/files/7505721/Katalog.poziadaviek.docx)
Posledná verzia (vo Worde)

**Comment by msabolova149** [comment]
Najnovšia verzia:
https://docs.google.com/document/d/18pFWEjdw_67-LETfkEEUcbnFF3Clm3x6E9iJ-Qe-hT8/edit?usp=sharing
