### ISSUE TITLE
Podrobný dátový model perzistentných údajov

### ISSUE THREAD

**Issue by msabolova149** [TIS2021-FMFI/pomocky-a-skolenia#16]

**Comment by Jackulik3** [comment]
![pgERD](https://user-images.githubusercontent.com/91477400/141698415-72935cde-4ce2-4d41-a8f3-da11455aa167.png)

**Comment by Jackulik3** [comment]
Create script (PostgreSQL).
[createScript.txt](https://github.com/TIS2021-FMFI/pomocky-a-skolenia/files/7534652/createScript.txt)
