### ISSUE TITLE
Návrh implementácie - UML diagramy

### ISSUE THREAD

**Issue by msabolova149** [TIS2021-FMFI/pomocky-a-skolenia#8]
UML Diagramy - Class, Component a State

**Comment by msabolova149** [comment]
UML Class Diagram
<img width="772" alt="Screenshot (302)" src="https://user-images.githubusercontent.com/61238834/140645387-a641ed5c-9b0d-4ce7-b2fc-ed1979d626fc.png">

**Comment by m4rtin7** [comment]
component diagram
![image](https://user-images.githubusercontent.com/79214528/140754150-bde780d9-6e1e-474c-8e47-35b3b4ee4ea2.png)

**Comment by Jackulik3** [comment]
State diagram
![State](https://user-images.githubusercontent.com/91477400/140758528-22316876-83aa-46ed-9778-d3de85d454a6.png)
